### ISSUE TITLE
Questions about run eval.sh

### ISSUE THREAD

**Issue by gemcollector** [nicklashansen/policy-adaptation-during-deployment#4]
When I run: bash script/eval.sh
I met the below problem:
`
Traceback (most recent call last):
  File "/home/yzc/anaconda3/envs/py37/lib/python3.7/site-packages/IPython/core/interactiveshell.py", line 3437, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-2-b973f175d723>", line 1, in <module>
    state = env.reset()
  File "/home/yzc/policy-adaptation-during-deployment/src/env/wrappers.py", line 60, in reset
    self.randomize()
  File "/home/yzc/policy-adaptation-during-deployment/src/env/wrappers.py", line 76, in randomize
    self.reload_physics(self.get_random_color())
  File "/home/yzc/policy-adaptation-during-deployment/src/env/wrappers.py", line 87, in reload_physics
    domain_name = self._get_dmc_wrapper()._domain_name
  File "/home/yzc/anaconda3/envs/py37/lib/python3.7/site-packages/dmc2gym/wrappers.py", line 99, in __getattr__
    return getattr(self._env, name)
AttributeError: 'Environment' object has no attribute '_domain_name'
`

**Comment by nicklashansen** [comment]
Hi, thank you for reaching out. You will need to follow the setup steps in the readme to install custom dmc2gym and dm_control packages with support for randomized test environments.

**Comment by gemcollector** [comment]
> Hi, thank you for reaching out. You will need to follow the setup steps in the readme to install custom dmc2gym and dm_control packages with support for randomized test environments.

Thanks for your reply! I solved this problems
